server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: tiger

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

app:
  service-name: Identity Service
  message: Identity configuration loaded from GitHub


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
